apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    role: production
    stack: web
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP